appdj/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('location/', include('location.urls', namespace='location')),
    path('equipments/', include('equipments.urls', namespace='equipments')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

location/urls.py
from django.urls import path
from . import views

app_name = 'location'

urlpatterns = [
    path('', views.List.as_view(), name='list'),
    path('<int:id>/', views.List.as_view(), name='list'),
    path('<int:id>/create/', views.Create.as_view(), name='create'),
    path('<int:id>/update/', views.Update.as_view(), name='update'),
    path('<int:id>/delete/', views.Delete.as_view(), name='delete'),
]

location/models.py
from django.db import models
from mptt.models import MPTTModel, TreeForeignKey
from django.urls import reverse


class Address(MPTTModel):
    """
        Class that manages the address model fields
    """
    name = models.CharField(max_length=50)
    parent = TreeForeignKey('self', on_delete=models.PROTECT, null=True, blank=True, related_name='children')

    def __str__(self):
        return self.name

    class MPTTMeta:
        order_insertion_by = ['name']

    def get_absolute_url(self):
        return reverse('location:update', kwargs={'pk': self.pk})

location/forms.py
from django import forms
from .models import Address
from django.urls import reverse


class AdrForm(forms.ModelForm):
    name = forms.CharField(
        min_length=2,
        max_length=50,
        label="Название",
        widget=forms.TextInput(
            attrs={
                'class': 'form-control',
                'placeholder': 'Адрес'
            }
        )
    )

    class Meta:
        model = Address
        fields = ['name']

    def get_absolute_url(self):
        return reverse("location:list", kwargs={"id": self.id})

location/views.py
from django.shortcuts import render, get_object_or_404, redirect

from django.views import View
from django.views.generic.edit import DeleteView
from django.urls import reverse_lazy

from django.core.paginator import Paginator
from django.core.paginator import EmptyPage
from django.core.paginator import PageNotAnInteger

from .models import Address
from .forms import AdrForm


class List(View):
    template_name = "location/address_list.html"
    model = Address
    paginate = 25

    def get(self, request, *args, **kwargs):
        parents = [{'id': 0, 'name': 'root'}]

        _id = kwargs.get('id')

        if (_id is not None) and (_id > 0):
            # Get all parents
            q = Address.objects.filter(parent_id=_id)
            pr = Address.objects.get(id=_id)

            for parent in pr.get_ancestors(ascending=False, include_self=False):
                parents.append({'id': parent.id, 'name': parent.name})

            parents.append({'id': pr.id, 'name': pr.name})

        else:
            # Get root tree
            q = Address.objects.filter(level=0)

        # Pagination
        paginator = Paginator(q, self.paginate)
        page = self.request.GET.get('page')

        try:
            adr = paginator.page(page)
        except PageNotAnInteger:
            adr = paginator.page(1)
        except EmptyPage:
            adr = paginator.page(paginator.num_pages)

        # Context
        context = {
            'object_list': adr,
            'parents': parents,
        }

        return render(request, self.template_name, context)


class Create(View):
    """
        Class that allows you to new a Address object.
    """
    template_name = "location/address_form_create.html"
    model = Address
    form = AdrForm

    def get(self, request, *args, **kwargs):
        return render(request, self.template_name, {'form': self.form(),})

    def post(self, request, *args, **kwargs):
        form = self.form(request.POST)
        if form.is_valid():
            parent_id = kwargs.get('id')

            model_adr = self.model()

            model_adr.name = form.cleaned_data['name']
            model_adr.parent_id = parent_id
            model_adr.save()

            return redirect('location:list', id=parent_id)

        context = {"form": form}
        return render(request, self.template_name, context)


class Update(View):
    """
        Class that allows you to update a Address object.
    """
    template_name = "location/address_form_update.html"
    model = Address
    form = AdrForm

    def get(self, request, *args, **kwargs):
        adr = get_object_or_404(self.model, id = kwargs.get('id'))
        return render(request, self.template_name, {'form': self.form(initial={'name': adr.name,})})

    def post(self, request, *args, **kwargs):
        form = self.form(request.POST)
        if form.is_valid():
            adr = get_object_or_404(self.model, id=kwargs.get('id'))
            adr.name = form.cleaned_data['name']
            adr.save()

            return redirect('location:list', id=adr.parent_id)

        context = {"form": form}
        return render(request, self.template_name, context)


class Delete(DeleteView):
    """
    Class that allows you to delete a Address object.
    """
    model = Address
    success_url = reverse_lazy('location:list')

    def get_object(self):
        id_ = self.kwargs.get("id")
        adr = get_object_or_404(Address, id=id_)

        self.success_url = reverse_lazy('location:list', kwargs={'id': adr.parent_id})
        return adr

location/templates/location/address_confirm_delete.html
{% extends "base.html" %}
{% block title %}Удаления адреса - {{ block.super }}{% endblock %}

{% block content %}

<div class="box box-solid box-danger">
    <div class="box-header with-border">
      <h3 class="box-title">Удалить адрес?</h3>
    </div>
    <!-- /.box-header -->
    <!-- form start -->  
      <form action='.' method='POST'>
            <div class="box-body">
                {% csrf_token %}
                <h3>Удалить адрес "{{ object.name }}" из cправочника?</h3>
    <div class="box-footer">
            <div class="pull-right">
                <button class="btn btn-danger" type="submit" value='Yes'>Удалить</button>
                <a class="btn btn-warning" href="{% url 'location:list' %}">Отменить</a>
            </div>
        </div>
    </div><!-- /.box-body -->
</form>
</div>

{% endblock %}

location/templates/location/address_form.html
{% extends "base.html" %}
{% block title %}Добавить новый адрес - {{ block.super }}{% endblock %}

{% block page_name %}Добавить новый адрес{% endblock %}

{% block content %}

<div class="box box-primary">
    <div class="box-header with-border">
      <h3 class="box-title">Добавить новый адрес</h3>
    </div>
    <!-- /.box-header -->
    <!-- form start -->  
      <form class="form-horizontal" action='.' method='POST' role="form">
            <div class="box-body">
                {% csrf_token %}

                {% for error in form.non_field_errors %}                   
                <div class="form-group has-errors text-danger">
                    {{error}}
                </div>
                {% endfor %}

                {% for field in form %}

                    {% if field.is_hidden %}
                        {{field}}
                    {% else %}
                        <div class="form-group has-errors text-danger">
                            {{field.errors}}
                        </div>
                        <div class="form-group">
                            <label class="col-sm-2 control-label" for="id_{{ field.name }}">{{ field.label }}</label>
                            <div class="col-sm-8">{{field}}</div>
                        </div>
                    {% endif %}
                
                {% endfor %}

                <div class="box-footer">
                    <div class="pull-right">
                        <button type="submit" class="btn btn-success">Добавить</button>
                        <a class="btn btn-warning" href="{% url 'location:list' %}">Отменить</a>
                    </div>
                </div>
            </div><!-- /.box-body -->
        </form>
  </div>




{% endblock %}

location/templates/location/address_form_create.html
{% extends "base.html" %}
{% block title %}Добавить новый адрес - {{ block.super }}{% endblock %}

{% block page_name %}Добавить новый адрес{% endblock %}

{% block content %}

<div class="box box-primary">
    <div class="box-header with-border">
      <h3 class="box-title">Добавить новый адрес</h3>
    </div>
    <!-- /.box-header -->
    <!-- form start -->  
      <form class="form-horizontal" action='.' method='POST' role="form">
            <div class="box-body">
                {% csrf_token %}

                {% for error in form.non_field_errors %}                   
                <div class="form-group has-errors text-danger">
                    {{error}}
                </div>
                {% endfor %}

                {% for field in form %}

                    {% if field.is_hidden %}
                        {{field}}
                    {% else %}
                        <div class="form-group has-errors text-danger">
                            {{field.errors}}
                        </div>
                        <div class="form-group">
                            <label class="col-sm-2 control-label" for="id_{{ field.name }}">{{ field.label }}</label>
                            <div class="col-sm-8">{{field}}</div>
                        </div>
                    {% endif %}
                
                {% endfor %}

                <div class="box-footer">
                    <div class="pull-right">
                        <button type="submit" class="btn btn-success">Добавить</button>
                        <a class="btn btn-warning" onClick="javascript:history.go(-1);">Отменить</a>
                    </div>
                </div>
            </div><!-- /.box-body -->
        </form>
  </div>

{% endblock %}

location/templates/location/address_form_update.html
{% extends "base.html" %}
{% block title %}Редактировать адрес - {{ block.super }}{% endblock %}

{% block page_name %}Редактировать адрес{% endblock %}

{% block content %}

<div class="box box-primary">
    <div class="box-header with-border">
      <h3 class="box-title">Редактировать адрес</h3>
    </div>
    <!-- /.box-header -->
    <!-- form start -->  
      <form class="form-horizontal" action='.' method='POST' role="form">
            <div class="box-body">
                {% csrf_token %}

                {% for error in form.non_field_errors %}                   
                <div class="form-group has-errors text-danger">
                    {{error}}
                </div>
                {% endfor %}

                {% for field in form %}

                    {% if field.is_hidden %}
                        {{field}}
                    {% else %}
                        <div class="form-group has-errors text-danger">
                            {{field.errors}}
                        </div>
                        <div class="form-group">
                            <label class="col-sm-2 control-label" for="id_{{ field.name }}">{{ field.label }}</label>
                            <div class="col-sm-8">{{field}}</div>
                        </div>
                    {% endif %}
                
                {% endfor %}

                <div class="box-footer">
                    <div class="pull-right">
                        <button type="submit" class="btn btn-success">Сохранить</button>
                        <a class="btn btn-warning" onClick="javascript:history.go(-1);">Отменить</a>
                    </div>
                </div>
            </div><!-- /.box-body -->
        </form>
  </div>




{% endblock %}

location/templates/location/address_list.html
{% extends "base.html" %}
{% block title %}Каталог адресов - {{ block.super }}{% endblock %}

{% block page_name %}Каталог адресов{% endblock %}

{% block content %}

    <div class="box">
        <div class="box-header with-border">

            {% for parent in parents %}
                {% if parent.id == 0 %}
                    <a class="btn btn-primary" href="{% url 'location:list' %}"><i class="fa fa-th-large"></i></a>
                {% else %}
                    <a class="btn btn-primary" href="{% url 'location:list' parent.id %}">{{ parent.name }}</a>
                {% endif %}
            {% endfor %}

            <div class="box-tools pull-right">
                {% with parents|last as current_parent %}
                    <a class="btn btn-success" href="{% url 'location:create' current_parent.id %}"><i
                            class="fa fa-plus"></i> Создать</a>
                {% endwith %}

            </div><!-- /.box-tools -->
        </div>
        <!-- /.box-header -->
        <div class="box-body">
            <table class="table table-bordered">
                <tbody>
                <tr>
                    <th class="col-sm-10">Местоположение</th>
                    <th class="col-sm-1">Найти</th>
                    <th class="col-sm-1">Действия</th>
                </tr>
                {% for address in object_list %}
                    <tr>
                        {% if address.level < 2 %}
                            <td>
                                <a href="{% url 'location:list' address.id %}">{{ address.name }}</a>
                            </td>
                            <td>
                                Недоступно
                            </td>
                        {% else %}
                            <td>
                                {{ address.name }}
                            </td>
                            <td>
                                <a class="btn btn-primary" href="#">
                                    <i class="fa fa-cogs"></i>
                                </a>
                                <a class="btn btn-primary" href="#"><i class="fa fa-users"></i></a>
                            </td>
                        {% endif %}

                        <td>
                            <a class="btn btn-warning" href="{% url 'location:update' address.id %}">
                                <i class="fa fa-edit"></i>
                            </a>
                            <a class="btn btn-danger" href="{% url 'location:delete' address.id %}">
                                <i class="fa fa-trash-o"></i>
                            </a>
                        </td>
                    </tr>
                {% empty %}
                    <tr>
                        <td>нет записей</td>
                        <td></td>
                        <td></td>
                    </tr>

                {% endfor %}

                </tbody>
            </table>
        </div>
        <!-- /.box-body -->
        <div class="box-footer clearfix">

        </div>
    </div>


    {% include "paginate.html" %}

{% endblock %}

location/templates/location/index.html
{% extends "base.html" %}
{% block title %}Index{% endblock %}
{% block body %}
  <h1>Hello! this is the Index template.</h1>
{% endblock %}